### ISSUE TITLE
Custom CA Certs error

### ISSUE THREAD

**Issue by Pibotasnus** [AzBuilder/docs#15]
Hello,
I have noticed that there is a probleme in the page https://docs.terrakube.io/getting-started/deployment/custom-ca-certs

The error is that the snippet of the values.yaml under values and items:

```
  - key: "type'
     path: "type"
```
Should be "type"

**Comment by alfespa17** [comment]
thank you @Pibotasnus , I fixed it

![image](https://github.com/user-attachments/assets/8810e59c-d8bd-4831-8c2f-d48e2256cfc2)
