### ISSUE TITLE
'edit on github' LInks to edit docs do not work.

### ISSUE THREAD

**Issue by defenestration** [AzBuilder/docs#8]
This link does not seem to work. Tried a few pages and they are all similar. 

![image](https://github.com/AzBuilder/docs/assets/961130/c6c37255-4c93-450d-b767-4a96cd6fad1d)

One example on https://docs.terrakube.io/user-guide/private-registry/using-private-modules is directed to https://github.com/AzBuilder/docs.git/user-guide/private-registry/using-private-modules.md but this is not found.

**Comment by alfespa17** [comment]
Hello @defenestration 

This repository is connected to [gitbook](https://www.gitbook.com/), we use that tool to manage all the documentation for Terrakube and it looks like the "edit on github" button has a bug in that tool.

I will check maybe I can find a way to fix the link inside the gitbook configuration

**Comment by jcanizalez** [comment]
The button is working now
